runtime: nodejs22

instance_class: F2

env_variables:
  NODE_ENV: "production"
  GEMINI_API_KEY: "REDACTED_GCP_API_KEY"

handlers:
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 3
  target_cpu_utilization: 0.65
